Reusable CICD for SciOps Workflows
dj-sciops/djsciops-cicd pull request #6
Opened 2022-06-01 18:48 UTC by yambottle

2022-06-01 22:06 UTC, guzman-raphael requested changes
@yambottle Great work! :construction_worker: 

Only adding minor points from our discussion.

2022-06-01 22:06 UTC, guzman-raphael commented on .github/.staging_workflows/anchored_sciops_docker_images.yaml
>            chmod 400 ${REPO_NAME}-deploy.pem
A bit more verbose but think this is a bit easier for reviews.

```suggestion
          chmod u=r,g-rwx,o-rwx ${REPO_NAME}-deploy.pem
```

2022-06-01 22:06 UTC, guzman-raphael commented on .github/.staging_workflows/anchored_sciops_docker_images.yaml
> +          find . -maxdepth 1 -type d \( -iname "*" ! -iname "*local*" \) | awk "NR>1" | cut -d/ -f2 | xargs -I {} bash -c \
Might make it a bit easier to work with if you use a heredoc. Here are some example references:
- https://linuxize.com/post/bash-heredoc/ (simple case)
- https://github.com/datajoint/miniconda3-docker/blob/fe9fb413af0a742ea5809b76ca9634cd00cf9d3e/tests/main.sh#L103-L107 (real world)

2022-06-02 21:52 UTC, drewyangdev commented on .github/.staging_workflows/anchored_sciops_docker_images.yaml
> +          find . -maxdepth 1 -type d \( -iname "*" ! -iname "*local*" \) | awk "NR>1" | cut -d/ -f2 | xargs -I {} bash -c \
xargs has issue working with heredoc... So I updated all xargs with while loop which is similar approach.

2022-06-06 15:43 UTC, guzman-raphael approved these changes
@yambottle Looking good! :sunglasses:

2022-06-06 15:48 UTC, merged